# Generated by Django 5.1.15 on 2026-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
