"""KAT-3: SEO-слаги товаров — /sortiment/<категория>/<товар>/ и /sortiment/p/<товар>/.

Слаг автогенерится в Product.save() при пустом и стабилен после создания;
uuid-роут остаётся жить (письма/QR/легаси). План
docs/kat-catalog-structure-plan-2026-08-18.md (батч 2)."""

from importlib import import_module

import pytest
from django.conf import settings as dj_settings
from django.http import Http404
from django.test import RequestFactory
from django.urls import resolve

from apps.catalog.models import Category, Product
from apps.catalog.tests.factories import ProductFactory
from apps.promotions import public_views
from apps.tenants.tests.factories import TenantFactory

pytestmark = pytest.mark.django_db


def _req(path="/"):
    request = RequestFactory().get(path)
    request.session = import_module(dj_settings.SESSION_ENGINE).SessionStore()
    request.tenant = TenantFactory.build()
    return request


def test_slug_autogenerated_and_unique():
    a = Product.objects.create(name={"de": "Bergkäse"}, base_price="4.90")
    b = Product.objects.create(name={"de": "Bergkäse"}, base_price="5.90")
    assert a.slug == "bergkaese" or a.slug == "bergkase"  # slugify умляута
    assert b.slug == f"{a.slug}-2"
    # слаг стабилен: повторный save и смена имени URL не меняют
    a.name = {"de": "Ganz anderer Name"}
    a.save()
    assert Product.objects.get(pk=a.pk).slug in ("bergkaese", "bergkase")


def test_slug_fallbacks():
    # без имени → sku; совсем пусто → 'eintrag'; bulk_create минует save → ""
    p = Product.objects.create(name={}, sku="ART-77", base_price="1.00")
    assert p.slug == "art-77"
    q = Product.objects.create(name={}, base_price="1.00")
    assert q.slug.startswith("eintrag")
    (r,) = Product.objects.bulk_create([Product(name={"de": "Bulk"}, base_price="1.00")])
    r.refresh_from_db()
    assert r.slug == ""
    assert r.get_absolute_url() == f"/sortiment/{r.pk}/"  # uuid-фолбэк


def test_absolute_url_by_category():
    cat = Category.objects.create(name={"de": "Käse"}, slug="ps-kaese")
    p = ProductFactory(category=cat)
    q = ProductFactory()  # без категории
    assert p.get_absolute_url() == f"/sortiment/ps-kaese/{p.slug}/"
    assert q.get_absolute_url() == f"/sortiment/p/{q.slug}/"


def test_seo_routes_resolve_and_render():
    cat = Category.objects.create(name={"de": "Käse"}, slug="ps-kaese2")
    p = ProductFactory(category=cat, name={"de": "Bergkäse Alt"})
    q = ProductFactory(name={"de": "Ohne Kategorie"})

    match = resolve(p.get_absolute_url(), urlconf="config.urls_tenant")
    assert match.url_name == "storefront-product-seo"
    match2 = resolve(q.get_absolute_url(), urlconf="config.urls_tenant")
    assert match2.url_name == "storefront-product-slug"

    html = public_views.product_detail(
        _req(p.get_absolute_url()), cslug=cat.slug, pslug=p.slug
    ).content.decode()
    assert "Bergkäse Alt" in html
    html2 = public_views.product_detail(_req(q.get_absolute_url()), pslug=q.slug).content.decode()
    assert "Ohne Kategorie" in html2
    # uuid-роут продолжает жить (письма/QR)
    html3 = public_views.product_detail(_req(f"/sortiment/{p.pk}/"), pk=p.pk).content.decode()
    assert "Bergkäse Alt" in html3


def test_seo_route_strict_category_match():
    """Чужая категория в пути → 404 (не дублируем контент по любым адресам);
    товар С категорией не отвечает на /sortiment/p/<slug>/."""
    cat = Category.objects.create(name={"de": "Wurst"}, slug="ps-wurst")
    other = Category.objects.create(name={"de": "Brot"}, slug="ps-brot")
    p = ProductFactory(category=cat)
    with pytest.raises(Http404):
        public_views.product_detail(_req("/x/"), cslug=other.slug, pslug=p.slug)
    with pytest.raises(Http404):
        public_views.product_detail(_req("/x/"), pslug=p.slug)


def test_cards_link_to_seo_url():
    """Карточки листинга и прайс-строки ведут на SEO-URL (get_absolute_url)."""
    cat = Category.objects.create(name={"de": "Deko"}, slug="ps-deko")
    p = ProductFactory(category=cat, name={"de": "Vase Nord"})
    html = public_views.product_list(_req("/sortiment/")).content.decode()
    assert p.get_absolute_url() in html
    assert f'href="/sortiment/{p.pk}/"' not in html


def test_category_cannot_take_reserved_p():
    """Слаг 'p' зарезервирован под подпуть товаров — unique_slug суффиксует."""
    from apps.catalog.slugs import unique_slug

    assert unique_slug(Category, "p") == "p-1"
