# Generated by Django 5.1.15 on 2026-06-13 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("promotions", "0013_alter_customer_created_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="StayUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room", "Zimmer"),
                            ("apartment", "Ferienwohnung"),
                            ("house", "Ferienhaus"),
                            ("bed", "Bett (Schlafsaal)"),
                            ("pitch", "Stellplatz"),
                        ],
                        default="room",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("min_nights", models.PositiveSmallIntegerField(default=1)),
                ("max_guests", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                ("deposit_cents", models.PositiveIntegerField(default=0)),
                ("require_manual_confirm", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=120)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="stays.stayunit",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="StayBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_code", models.CharField(max_length=12, unique=True)),
                ("arrival", models.DateField()),
                ("departure", models.DateField()),
                ("guests", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("source_channel", models.CharField(blank=True, max_length=50)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("deposit_cents", models.PositiveIntegerField(default=0)),
                (
                    "payment_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="promotions.customer",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="stays.stayunit",
                    ),
                ),
            ],
            options={
                "ordering": ["arrival"],
                "indexes": [
                    models.Index(
                        fields=["unit", "arrival"], name="stay_unit_arrival_idx"
                    ),
                    models.Index(
                        fields=["status", "arrival"], name="stay_status_arrival_idx"
                    ),
                ],
            },
        ),
    ]
