# Generated by Django 5.1.15 on 2026-06-15 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="total_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stayunit",
            name="weekend_price_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SeasonRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price_cents", models.PositiveIntegerField(default=0)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_rates",
                        to="stays.stayunit",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
