# Generated by Django 5.1.15 on 2026-06-15 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0003_backfill_total_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitblock",
            name="source_id_ref",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name="ICalSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("url", models.URLField(max_length=500)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ical_sources",
                        to="stays.stayunit",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
    ]
