# Generated by Django 5.1.15 on 2026-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0004_unitblock_source_id_ref_icalsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="invoice_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
