# Generated by Django 5.1.15 on 2026-06-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0005_staybooking_invoice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stayunit",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
