# Generated by Django 5.1.15 on 2026-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0006_stayunit_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="extras",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
