# Generated by Django 5.1.15 on 2026-06-22 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0007_staybooking_extras"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("percent_adjust", models.SmallIntegerField(default=0)),
                ("surcharge_cents", models.PositiveIntegerField(default=0)),
                (
                    "meal_plan",
                    models.CharField(
                        choices=[
                            ("none", "Ohne Verpflegung"),
                            ("breakfast", "Frühstück"),
                            ("half_board", "Halbpension"),
                            ("full_board", "Vollpension"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "cancellation",
                    models.CharField(
                        choices=[
                            ("flexible", "Kostenlose Stornierung"),
                            ("non_refundable", "Nicht erstattbar"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                ("free_cancel_days", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="staybooking",
            name="rate_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="staybooking",
            name="rate_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="stays.rateplan",
            ),
        ),
    ]
