# Generated by Django 5.1.15 on 2026-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0008_rateplan_staybooking_rate_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stayunit",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="stayunit",
            name="area_sqm",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stayunit",
            name="bed_type",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
