# Generated by Django 5.1.15 on 2026-06-22 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0009_stayunit_amenities_stayunit_area_sqm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kurtaxe_cents", models.PositiveIntegerField(default=0)),
                ("kurtaxe_label", models.CharField(default="Kurtaxe", max_length=80)),
                ("kurtaxe_children_free", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Stay settings",
                "verbose_name_plural": "Stay settings",
            },
        ),
        migrations.AddField(
            model_name="staybooking",
            name="adults",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="staybooking",
            name="children",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staybooking",
            name="kurtaxe_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
