# Generated by Django 5.1.15 on 2026-06-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0010_staysettings_staybooking_adults_staybooking_children_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staybooking",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
