# Generated by Django 5.1.15 on 2026-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0011_staybooking_discount_cents_staybooking_voucher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="staysettings",
            name="house_rules",
            field=models.TextField(blank=True),
        ),
    ]
