# Generated by Django 5.1.15 on 2026-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0012_staysettings_house_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="post_stay_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
