# Generated by Django 5.1.15 on 2026-06-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0013_staybooking_post_stay_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="auto_discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staybooking",
            name="auto_discount_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="early_bird_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="early_bird_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="last_minute_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="last_minute_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="los_discount_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="los_min_nights",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
