# Generated by Django 5.1.15 on 2026-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0014_staybooking_auto_discount_cents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateplan",
            name="prepayment_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
