# Generated by Django 5.1.15 on 2026-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0015_rateplan_prepayment_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="rooms",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
