# Generated by Django 5.1.15 on 2026-06-23 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0016_staybooking_rooms"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_name", models.CharField(max_length=120)),
                ("first_name", models.CharField(max_length=120)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=80)),
                ("street", models.CharField(blank=True, max_length=200)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("doc_type", models.CharField(blank=True, max_length=40)),
                ("doc_number", models.CharField(blank=True, max_length=60)),
                ("accompanying", models.PositiveSmallIntegerField(default=0)),
                ("signed_name", models.CharField(max_length=200)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration",
                        to="stays.staybooking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
