# Generated by Django 5.1.15 on 2026-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0017_guestregistration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staysettings",
            name="early_bird_days",
        ),
        migrations.RemoveField(
            model_name="staysettings",
            name="early_bird_percent",
        ),
        migrations.RemoveField(
            model_name="staysettings",
            name="last_minute_days",
        ),
        migrations.RemoveField(
            model_name="staysettings",
            name="last_minute_percent",
        ),
        migrations.RemoveField(
            model_name="staysettings",
            name="los_discount_percent",
        ),
        migrations.RemoveField(
            model_name="staysettings",
            name="los_min_nights",
        ),
        migrations.AddField(
            model_name="staysettings",
            name="auto_discount_rules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
