# Generated by Django 5.1.15 on 2026-06-24 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0018_remove_staysettings_early_bird_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking", "Booking.com"),
                            ("airbnb", "Airbnb"),
                            ("expedia", "Expedia"),
                            ("other", "Anderer Kanal"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
        migrations.AddField(
            model_name="staybooking",
            name="external_ref",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
