# Generated by Django 5.1.15 on 2026-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stays", "0019_channel_staybooking_external_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="stayunit",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="stayunit",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
