# Generated by Django 5.1.15 on 2026-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
        ("stays", "0020_stayunit_description_i18n_stayunit_name_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="stayunit",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="stay_units", to="collections.collection"
            ),
        ),
    ]
