# Generated by Django 5.1.15 on 2026-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0021_stayunit_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="payment_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
