# Generated by Django 5.1.15 on 2026-07-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0022_staybooking_payment_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="rateplan",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="rateplan",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="house_rules_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
