# Generated by Django 5.1.15 on 2026-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0023_rateplan_description_i18n_rateplan_name_i18n_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staysettings",
            name="max_advance_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="min_advance_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="restriction_rules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
