# Generated by Django 5.1.15 on 2026-07-27 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0024_staysettings_max_advance_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="stays.stayunit",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "number"), name="stays_room_unique_number"
                    )
                ],
            },
        ),
    ]
