# Generated by Django 5.1.15 on 2026-07-27 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0025_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="stays.room",
            ),
        ),
    ]
