# Generated by Django 5.1.15 on 2026-07-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0026_staybooking_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="housekeeping",
            field=models.CharField(
                choices=[
                    ("clean", "Sauber"),
                    ("dirty", "Zu reinigen"),
                    ("inspected", "Geprüft"),
                ],
                default="clean",
                max_length=12,
            ),
        ),
    ]
