# Generated by Django 5.1.15 on 2026-07-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0027_room_housekeeping"),
    ]

    operations = [
        migrations.AddField(
            model_name="staysettings",
            name="occupancy_rules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
