# Generated by Django 5.1.15 on 2026-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0028_staysettings_occupancy_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="staysettings",
            name="gap_discount_percent",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="staysettings",
            name="gap_max_nights",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
