# Generated by Django 5.1.15 on 2026-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0029_staysettings_gap_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stayunit",
            name="gap_discount_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stayunit",
            name="gap_max_nights",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
