# Generated by Django 5.1.15 on 2026-08-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0025_promotion_combo_promotion_service_and_more"),
        ("stays", "0030_stayunit_gap_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stay_bookings",
                to="promotions.promotion",
            ),
        ),
    ]
