# Generated by Django 5.1.15 on 2026-08-13 22:47

import apps.secrets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0031_staybooking_promotion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestregistration",
            name="doc_number",
            field=apps.secrets.fields.EncryptedTextField(blank=True),
        ),
    ]
