# Generated by Django 5.1.15 on 2026-08-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0032_alter_guestregistration_doc_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="external_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
