# Generated by Django 5.1.15 on 2026-08-26 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stays", "0033_staybooking_external_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="staybooking",
            name="discount_scope",
            field=models.CharField(
                choices=[("deal", "Ganze Buchung"), ("position", "Übernachtung")],
                default="deal",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="staybooking",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("7.00"), max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="stayunit",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("7.00"), max_digits=4
            ),
        ),
    ]
