# Generated by Django 5.1.15 on 2026-06-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="program",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
