# Generated by Django 5.1.15 on 2026-06-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
