# Generated by Django 5.1.15 on 2026-06-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_details_event_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tiers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tier_label",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
