# Generated by Django 5.1.15 on 2026-06-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_tiers_ticket_tier_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="extras",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
