# Generated by Django 5.1.15 on 2026-06-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_taxonomy"),
        ("stays", "0019_channel_staybooking_external_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="accommodation_units",
            field=models.ManyToManyField(
                blank=True, related_name="retreat_events", to="stays.stayunit"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="offers_accommodation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="accommodation_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="stay_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_tickets",
                to="stays.staybooking",
            ),
        ),
    ]
