# Generated by Django 5.1.15 on 2026-06-24 11:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_accommodation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("title", models.CharField(blank=True, max_length=160)),
                ("bio", models.TextField(blank=True)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("instagram", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.teacher"
            ),
        ),
    ]
