# Generated by Django 5.1.15 on 2026-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_teacher_event_teachers"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="deposit_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="deposit_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ticket",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("deposit", "Deposit paid"),
                    ("refunded", "Refunded"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
