# Generated by Django 5.1.15 on 2026-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_ticket_voucher_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
