# Generated by Django 5.1.15 on 2026-06-24 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_event_geo"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="waiver_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="waiver_text",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="TicketWaiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("waiver_text_snapshot", models.TextField()),
                ("health_confirmed", models.BooleanField(default=False)),
                ("signed_name", models.CharField(max_length=200)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiver",
                        to="events.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
