# Generated by Django 5.1.15 on 2026-06-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_waiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="post_event_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
