# Generated by Django 5.1.15 on 2026-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_ticket_drip"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="cancellation",
            field=models.CharField(
                choices=[
                    ("flexible", "Kostenlose Stornierung"),
                    ("non_refundable", "Nicht erstattbar"),
                ],
                default="flexible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="free_cancel_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
