# Generated by Django 5.1.15 on 2026-06-24 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_cancellation_event_free_cancel_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_installments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="installment_count",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="event",
            name="installment_lead_days",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="event",
            name="installment_min_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="installment_mode",
            field=models.CharField(
                choices=[
                    ("until_event", "Bis zur Veranstaltung"),
                    ("fixed", "Feste Monatsraten"),
                ],
                default="until_event",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InstallmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_cents", models.PositiveIntegerField(default=0)),
                ("count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("stripe_customer_id", models.CharField(blank=True, max_length=120)),
                (
                    "stripe_payment_method_id",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_plan",
                        to="events.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstallmentCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="scheduled",
                        max_length=12,
                    ),
                ),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="events.installmentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "sequence"), name="uniq_plan_sequence"
                    )
                ],
            },
        ),
    ]
