# Generated by Django 5.1.15 on 2026-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_event_allow_installments_event_installment_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("deposit", "Deposit paid"),
                    ("installment", "Installment plan"),
                    ("refunded", "Refunded"),
                ],
                default="none",
                max_length=12,
            ),
        ),
    ]
