# Generated by Django 5.1.15 on 2026-06-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_ticket_payment_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="online_url",
            field=models.URLField(blank=True),
        ),
    ]
