# Generated by Django 5.1.15 on 2026-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_is_online_event_online_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
