# Generated by Django 5.1.15 on 2026-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_ticket_checked_in_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="series_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
