# Generated by Django 5.1.15 on 2026-06-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
