# Generated by Django 5.1.15 on 2026-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_description_i18n_event_title_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payment_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
