# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_ticket_payment_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="body_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="details_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="program_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="questions_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bio_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="teacher",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
