# Generated by Django 5.1.15 on 2026-08-13 22:00

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Перенумеровано при ребейзе: main параллельно добавил 0023 (I18N-12).
        ("events", "0023_blogpost_body_i18n_blogpost_excerpt_i18n_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("title_i18n", models.JSONField(blank=True, default=dict)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("summary_i18n", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                ("description_i18n", models.JSONField(blank=True, default=dict)),
                ("images", models.JSONField(blank=True, default=list)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("itinerary", models.JSONField(blank=True, default=list)),
                ("region", models.CharField(blank=True, max_length=120)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Leicht"),
                            ("medium", "Mittel"),
                            ("hard", "Anspruchsvoll"),
                        ],
                        max_length=20,
                    ),
                ),
                ("distance_km", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(blank=True, default=0),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, default=0)),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True, related_name="tours", to="events.teacher"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
            bases=(apps.core.models.I18nMixin, models.Model),
        ),
        migrations.AddField(
            model_name="event",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departures",
                to="events.tour",
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["is_published", "sort_order"], name="tour_pub_sort_idx"
            ),
        ),
    ]
