# Generated by Django 5.1.15 on 2026-08-14 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("events", "0024_tour_and_event_departure"),
        ("inventory", "0004_stocklocation_alter_stockmovement_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hotel", "Unterkunft"),
                            ("transport", "Transport / Tickets"),
                            ("excursion", "Ausflug"),
                            ("permit", "Permit / Genehmigung"),
                            ("guide", "Guide vor Ort"),
                            ("other", "Sonstiges"),
                        ],
                        default="hotel",
                        max_length=20,
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("day", models.PositiveSmallIntegerField(default=0)),
                ("date", models.DateField(blank=True, null=True)),
                ("stop", models.CharField(blank=True, max_length=200)),
                ("qty", models.PositiveSmallIntegerField(default=1)),
                ("cost_cents", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "amount_original",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_book", "Zu buchen"),
                            ("requested", "Angefragt"),
                            ("confirmed", "Bestätigt"),
                            ("paid", "Bezahlt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="to_book",
                        max_length=20,
                    ),
                ),
                ("confirmation_ref", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("visible_to_participants", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.securedocument",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_bookings",
                        to="events.event",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.lieferant",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"], name="supbook_event_status_idx"
                    )
                ],
            },
        ),
    ]
