# Generated by Django 5.1.15 on 2026-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_tourtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="country",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="tour",
            name="country_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tour",
            name="details_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tour",
            name="itinerary_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tour",
            name="region_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
