# Generated by Django 5.1.15 on 2026-08-21 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0027_tour_country_and_i18n_overlays"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierbooking",
            name="ref_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="supplierbooking",
            name="ref_kind",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="supplierbooking",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_bookings",
                to="events.event",
            ),
        ),
    ]
