# Generated by Django 5.1.15 on 2026-08-26 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_supplierbooking_ref_id_supplierbooking_ref_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="discount_scope",
            field=models.CharField(
                choices=[("deal", "Ganzes Ticket"), ("position", "Tarif")],
                default="deal",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=4
            ),
        ),
    ]
