# Generated by Django 5.1.15 on 2026-07-03 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "reward_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("client_discount", "Rabatt für Kunden (Stripe-Coupon)"),
                            ("revshare", "Revenue-Share (Auszahlung manuell)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "revshare_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
