# Generated by Django 5.1.15 on 2026-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_variant_orderitem_variant_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment",
            field=models.CharField(
                choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                default="pickup",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("confirmed", "Confirmed"),
                    ("ready", "Ready"),
                    ("picked_up", "Picked up"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
