# Generated by Django 5.1.15 on 2026-06-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_fulfillment_order_shipped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="parent_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_orders",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_tenant_schema",
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
