# Generated by Django 5.1.15 on 2026-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_parent_order_order_supplier_tenant_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="modifiers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
