# Generated by Django 5.1.15 on 2026-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitem_modifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("confirmed", "Confirmed"),
                    ("ready", "Ready"),
                    ("picked_up", "Picked up"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Cancelled"),
                    ("returned", "Returned"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
