# Generated by Django 5.1.15 on 2026-06-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
