# Generated by Django 5.1.15 on 2026-06-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderitem_combo_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
