# Generated by Django 5.1.15 on 2026-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_discount_cents_order_voucher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
