# Generated by Django 5.1.15 on 2026-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_order_pickup_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_site", "Barzahlung bei Abholung"),
                    ("stripe", "Online-Zahlung"),
                    ("vorkasse", "Vorkasse (Überweisung)"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
