# Generated by Django 5.1.15 on 2026-07-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="post_purchase_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
