# Generated by Django 5.1.15 on 2026-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_post_purchase_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
