# Generated by Django 5.1.15 on 2026-07-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_offer_offerline"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reserve_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
