# Generated by Django 5.1.15 on 2026-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_order_reserve_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
