# Generated by Django 5.1.15 on 2026-08-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_orderitem_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="external_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
