# Generated by Django 5.1.15 on 2026-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_order_billing_address_order_billing_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
