# Generated by Django 5.1.15 on 2026-08-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_orderitem_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_scope",
            field=models.CharField(
                choices=[
                    ("deal", "Ganze Bestellung"),
                    ("position", "Position"),
                    ("delivery", "Versand"),
                ],
                default="deal",
                max_length=12,
            ),
        ),
    ]
