# Generated by Django 5.1.15 on 2026-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_order_discount_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerline",
            name="sku",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
