# Generated by Django 5.1.15 on 2026-09-03 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_sku_snapshot"),
        ("promotions", "0027_promotion_card_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="list_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="promo_label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="promotions.promotion",
            ),
        ),
    ]
