# Generated by Django 5.1.15 on 2026-06-13 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0011_tenant_orders_prepay"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageFeeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=7)),
                ("gmv_cents", models.PositiveIntegerField(default=0)),
                (
                    "fee_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("fee_cents", models.PositiveIntegerField(default=0)),
                (
                    "stripe_invoice_item_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_fees",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "period"), name="usagefee_tenant_period_uniq"
                    )
                ],
            },
        ),
    ]
