# Generated by Django 5.1.15 on 2026-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AggregatorListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_schema", models.CharField(max_length=63)),
                ("tenant_slug", models.SlugField(max_length=100)),
                ("business_name", models.CharField(max_length=200)),
                ("business_type", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("promo_uuid", models.UUIDField()),
                ("title", models.JSONField(default=dict)),
                ("teaser", models.JSONField(default=dict)),
                ("image", models.JSONField(blank=True, default=dict)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("detail_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["city", "is_active"], name="agg_city_active_idx"
                    ),
                    models.Index(
                        fields=["business_type", "city"], name="agg_btype_city_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_schema", "promo_uuid"), name="agg_listing_uniq"
                    )
                ],
            },
        ),
    ]
