# Generated by Django 5.1.15 on 2026-06-10 15:27

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0002_aggregatorlisting_is_surprise"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatorPortal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=253, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("vertical", "Vertical"),
                            ("combo", "City + type"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bakery", "Bakery / Bäckerei"),
                            ("butcher", "Butcher / Metzgerei"),
                            ("grocery", "Grocery / Lebensmittel"),
                            ("clothing", "Clothing / Bekleidung"),
                            ("restaurant", "Restaurant"),
                            ("cafe", "Cafe"),
                            ("retail", "Retail / Einzelhandel"),
                            ("tour_operator", "Tour Operator"),
                            ("hotel", "Hotel"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.JSONField(default=dict)),
                ("tagline", models.JSONField(blank=True, default=dict)),
                ("intro", models.JSONField(blank=True, default=dict)),
                ("logo_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#111827", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["host"],
                "indexes": [
                    models.Index(fields=["is_active"], name="agg_portal_active_idx")
                ],
            },
            bases=(apps.core.models.I18nMixin, models.Model),
        ),
    ]
