# Generated by Django 5.1.15 on 2026-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0005_favoritelisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="portaluser",
            name="marketing_opt_out",
            field=models.BooleanField(default=False),
        ),
    ]
