# Generated by Django 5.1.15 on 2026-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0006_portaluser_marketing_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="featured_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
