# Generated by Django 5.1.15 on 2026-06-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0007_aggregatorlisting_featured_until"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_schema", models.CharField(max_length=63, unique=True)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_schema", models.CharField(max_length=63)),
                ("tenant_slug", models.SlugField(max_length=100)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "Published"), ("hidden", "Hidden")],
                        default="published",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="aggregator.portaluser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_schema", "status"],
                        name="review_business_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("author", "tenant_schema"),
                        name="review_author_business_uniq",
                    )
                ],
            },
        ),
    ]
