# Generated by Django 5.1.15 on 2026-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0008_businessrating_businessreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
