# Generated by Django 5.1.15 on 2026-06-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0009_aggregatorlisting_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=100)),
                ("bot_username", models.CharField(blank=True, max_length=64)),
                ("webhook_secret", models.CharField(blank=True, max_length=48)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_bot",
                        to="aggregator.aggregatorportal",
                    ),
                ),
            ],
        ),
    ]
