# Generated by Django 5.1.15 on 2026-06-15 18:09

from django.db import migrations, models


def backfill_source_ref(apps, schema_editor):
    """Существующие листинги — все акции: source_ref = str(promo_uuid),
    listing_kind остаётся default 'promotion'. Нужен ДО нового unique
    (tenant_schema, listing_kind, source_ref), иначе пустые source_ref у
    нескольких листингов одного тенанта столкнутся."""
    Listing = apps.get_model("aggregator", "AggregatorListing")
    for row in Listing.objects.all().iterator():
        row.source_ref = str(row.promo_uuid) if row.promo_uuid else ""
        row.save(update_fields=["source_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0010_portalbot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aggregatorlisting",
            name="agg_listing_uniq",
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="listing_kind",
            field=models.CharField(
                choices=[
                    ("promotion", "Promotion"),
                    ("stay", "Stay"),
                    ("event", "Event"),
                ],
                default="promotion",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="source_ref",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="aggregatorlisting",
            name="promo_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_source_ref, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="aggregatorlisting",
            index=models.Index(
                fields=["listing_kind", "is_active"], name="agg_kind_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="aggregatorlisting",
            constraint=models.UniqueConstraint(
                fields=("tenant_schema", "listing_kind", "source_ref"),
                name="agg_listing_src_uniq",
            ),
        ),
    ]
