# Generated by Django 5.1.15 on 2026-07-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0013_aggregatorlisting_featured_payment_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="featured_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="featured_impressions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
