# Generated by Django 5.1.15 on 2026-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0015_alter_aggregatorportal_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessreview",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessreview",
            name="reply_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
