# Generated by Django 5.1.15 on 2026-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0016_businessreview_replied_at_businessreview_reply_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="diets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="dish_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="event_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="min_persons",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="price_per_person",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aggregatorlisting",
            name="listing_kind",
            field=models.CharField(
                choices=[
                    ("promotion", "Promotion"),
                    ("stay", "Stay"),
                    ("event", "Event"),
                    ("menu", "Menu"),
                ],
                default="promotion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="aggregatorportal",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bakery", "Bakery / Bäckerei"),
                    ("butcher", "Butcher / Metzgerei"),
                    ("grocery", "Grocery / Lebensmittel"),
                    ("clothing", "Clothing / Bekleidung"),
                    ("restaurant", "Restaurant"),
                    ("cafe", "Cafe"),
                    ("retail", "Retail / Einzelhandel"),
                    ("online_shop", "Online-Shop"),
                    ("tour_operator", "Tour Operator"),
                    ("hotel", "Hotel"),
                    ("friseur", "Friseur / Salon"),
                    ("handwerker", "Handwerker"),
                    ("werkstatt", "Werkstatt / KFZ"),
                    ("events", "Veranstalter / Events"),
                    ("catering", "Catering / Partyservice"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
