# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0017_menu_listings"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessreview",
            name="comment_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
