# Generated by Django 5.1.15 on 2026-10-09 18:15

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Существующие порталы сегодня все демонстрационные (hotels.<base> живёт на
    демо-отелях) — оставляем им показ демо. Листингам — флаг из тенанта."""
    Portal = apps.get_model("aggregator", "AggregatorPortal")
    Listing = apps.get_model("aggregator", "AggregatorListing")
    Tenant = apps.get_model("tenants", "Tenant")
    Portal.objects.update(show_demo=True)
    demo_schemas = list(Tenant.objects.filter(is_demo=True).values_list("schema_name", flat=True))
    Listing.objects.filter(tenant_schema__in=demo_schemas).update(is_demo=True)


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0033_t8_demo_district"),
        ("aggregator", "0018_businessreview_comment_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aggregatorportal",
            name="show_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
