# Generated by Django 5.1.15 on 2026-10-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0019_t8_demo_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="hidden_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.CreateModel(
            name="ListingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong", "Falsche Angaben"),
                            ("expired", "Angebot gibt es nicht mehr"),
                            ("offensive", "Anstößig oder rechtswidrig"),
                            ("spam", "Spam oder Betrug"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="", max_length=1000)),
                ("ip_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Offen"), ("resolved", "Erledigt")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="aggregator.aggregatorlisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="agg_report_queue_idx"
                    )
                ],
            },
        ),
    ]
