# Generated by Django 5.1.15 on 2026-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0020_t8_6_catalog_hygiene"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="city_category",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="city_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
