# Generated by Django 5.1.15 on 2026-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregator", "0021_t8_13a_city_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatorlisting",
            name="availability",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="aggregatorlisting",
            name="is_new",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aggregatorlisting",
            name="listing_kind",
            field=models.CharField(
                choices=[
                    ("promotion", "Promotion"),
                    ("stay", "Stay"),
                    ("event", "Event"),
                    ("menu", "Menu"),
                    ("product", "Produkt"),
                    ("service", "Dienstleistung"),
                    ("business", "Unternehmen"),
                ],
                default="promotion",
                max_length=20,
            ),
        ),
    ]
