# Generated by Django 5.1.15 on 2026-06-13 12:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("promotions", "0013_alter_customer_created_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_code", models.CharField(max_length=12, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("site_address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Anfrage"),
                            ("quoted", "Angebot gesendet"),
                            ("accepted", "Beauftragt"),
                            ("done", "Erledigt"),
                            ("invoiced", "Abgerechnet"),
                            ("declined", "Abgelehnt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("source_channel", models.CharField(blank=True, max_length=50)),
                (
                    "public_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("19.00"), max_digits=4
                    ),
                ),
                (
                    "net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("quoted_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("invoice_id", models.UUIDField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="promotions.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=300)),
                ("qty", models.PositiveSmallIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "created_at"], name="job_status_created_idx"
            ),
        ),
    ]
