# Generated by Django 5.1.15 on 2026-06-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_content_amount_product_unit_and_more"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="stock_committed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_lines",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="jobline",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_lines",
                to="catalog.productvariant",
            ),
        ),
    ]
