# Generated by Django 5.1.15 on 2026-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_stock_committed_jobline_product_jobline_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobline",
            name="qty",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
