# Generated by Django 5.1.15 on 2026-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_jobline_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deposit_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
