# Generated by Django 5.1.15 on 2026-06-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_resource_counts_party_size"),
        ("jobs", "0005_jobphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="booking.booking",
            ),
        ),
    ]
