# Generated by Django 5.1.15 on 2026-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_job_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="vehicle",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
