# Generated by Django 5.1.15 on 2026-06-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="vehicle_hsn",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="job",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="job",
            name="vehicle_tsn",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
