# Generated by Django 5.1.15 on 2026-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_job_vehicle_hsn_job_vehicle_plate_job_vehicle_tsn"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="site_plz",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
