# Generated by Django 5.1.15 on 2026-06-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_job_site_plz"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="service_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="service_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
