# Generated by Django 5.1.15 on 2026-07-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_job_service_due_date_job_service_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
