# Generated by Django 5.1.15 on 2026-07-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_discount_cents_job_voucher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
