# Generated by Django 5.1.15 on 2026-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_job_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="event_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="event_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="guest_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
