# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_job_event_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="jobline",
            name="text_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
