# Generated by Django 5.1.15 on 2026-08-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_job_description_i18n_job_title_i18n_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobline",
            name="cost_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
