# Generated by Django 5.1.15 on 2026-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_job_external_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobline",
            name="vat_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
