# Generated by Django 5.1.15 on 2026-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_jobline_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobline",
            name="sku",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
