# Generated by Django 5.1.15 on 2026-09-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_sku_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="fulfillment",
            field=models.CharField(
                blank=True,
                choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                max_length=10,
            ),
        ),
    ]
