# Generated by Django 5.1.15 on 2026-06-12 14:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("promotions", "0013_alter_customer_created_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevenueEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("reservation", "Reservation"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("19.00"), max_digits=4
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_entries",
                        to="promotions.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [models.Index(fields=["date"], name="revenue_date_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_ref", ""), _negated=True),
                        fields=("source", "source_ref"),
                        name="revenue_source_ref_uniq",
                    )
                ],
            },
        ),
    ]
