# Generated by Django 5.1.15 on 2026-06-12 16:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("promotions", "0013_alter_customer_created_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("issued", "Gestellt"),
                            ("paid", "Bezahlt"),
                            ("cancelled", "Storniert"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("recipient", models.TextField(blank=True)),
                ("lines", models.JSONField(default=list)),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("19.00"), max_digits=4
                    ),
                ),
                (
                    "net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="promotions.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
