# Generated by Django 5.1.15 on 2026-06-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_revenueentry_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("reservation", "Reservation"),
                    ("stay", "Stay"),
                    ("booking", "Booking"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
