# Generated by Django 5.1.15 on 2026-07-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_revenueentry_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="language",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
