# Generated by Django 5.1.15 on 2026-08-14 02:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_supplierbooking"),
        ("finance", "0006_invoice_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("supplier_booking", "Anbieter-Buchung"),
                            ("purchase", "Einkauf"),
                            ("manual", "Manuell"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("source_ref", models.CharField(blank=True, max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("original_currency", models.CharField(blank=True, max_length=3)),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=4
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accommodation", "Unterkunft"),
                            ("transport", "Transport"),
                            ("fees", "Gebühren / Permits"),
                            ("staff", "Personal vor Ort"),
                            ("goods", "Wareneinkauf"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_entries",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="expense_date_idx"),
                    models.Index(fields=["event"], name="expense_event_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_ref", ""), _negated=True),
                        fields=("source", "source_ref"),
                        name="expense_source_ref_uniq",
                    )
                ],
            },
        ),
    ]
