# Generated by Django 5.1.15 on 2026-08-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_expenseentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentry",
            name="ref_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="expenseentry",
            name="ref_kind",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
