# Generated by Django 5.1.15 on 2026-08-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_expenseentry_ref_id_expenseentry_ref_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenueentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("reservation", "Reservation"),
                    ("stay", "Stay"),
                    ("booking", "Booking"),
                    ("event", "Event"),
                    ("gift", "Geschenkgutschein"),
                    ("pass", "Mehrfachkarte"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
