# Generated by Django 5.1.15 on 2026-08-21 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_alter_revenueentry_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("purpose", models.CharField(blank=True, max_length=500)),
                ("counterparty", models.CharField(blank=True, max_length=200)),
                ("import_hash", models.CharField(max_length=32, unique=True)),
                ("matched_kind", models.CharField(blank=True, max_length=20)),
                ("matched_id", models.CharField(blank=True, max_length=64)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["matched_kind", "date"], name="banktx_matched_idx"
                    )
                ],
            },
        ),
    ]
