# Generated by Django 5.1.15 on 2026-08-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("finance", "0010_banktransaction"),
        ("inventory", "0004_stocklocation_alter_stockmovement_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentry",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.securedocument",
            ),
        ),
        migrations.AddField(
            model_name="expenseentry",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expenseentry",
            name="paid_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expenseentry",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.lieferant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mahn_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="mahned_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
