# Generated by Django 5.1.15 on 2026-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_expenseentry_document_expenseentry_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="deal_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deal_kind",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_terms_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
