# Generated by Django 5.1.15 on 2026-06-22 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("promotions", "0017_remove_loyaltycard_customer_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Перенос моделей между app'ами БЕЗ DDL: таблицы (promotions_*)
            # физически созданы историческими миграциями promotions и НЕ
            # пересоздаются — данные тенантов целы, свежие схемы получают те же.
            state_operations=[
                migrations.CreateModel(
                    name="LoyaltyProgram",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("label", models.CharField(max_length=120)),
                        ("stamps_required", models.PositiveSmallIntegerField(default=10)),
                        ("reward_label", models.CharField(max_length=120)),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "db_table": "promotions_loyaltyprogram",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="LoyaltyCard",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("stamps", models.PositiveIntegerField(default=0)),
                        ("rewards_earned", models.PositiveIntegerField(default=0)),
                        (
                            "token",
                            models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                        ),
                        (
                            "customer",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="loyalty_cards",
                                to="promotions.customer",
                            ),
                        ),
                        (
                            "program",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="cards",
                                to="loyalty.loyaltyprogram",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "promotions_loyaltycard",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="StampEvent",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "card",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="events",
                                to="loyalty.loyaltycard",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "promotions_stampevent",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="Voucher",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("code", models.CharField(max_length=12, unique=True)),
                        ("label", models.CharField(max_length=120)),
                        ("max_uses", models.PositiveIntegerField(default=1)),
                        ("used_count", models.PositiveIntegerField(default=0)),
                        ("is_active", models.BooleanField(default=True)),
                        ("expires_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "discount_percent",
                            models.PositiveSmallIntegerField(blank=True, null=True),
                        ),
                        ("discount_cents", models.PositiveIntegerField(blank=True, null=True)),
                        ("min_order_cents", models.PositiveIntegerField(default=0)),
                        (
                            "customer",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="vouchers",
                                to="promotions.customer",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "promotions_voucher",
                        "ordering": ["-created_at"],
                    },
                ),
                migrations.AddConstraint(
                    model_name="loyaltycard",
                    constraint=models.UniqueConstraint(
                        fields=("program", "customer"), name="uniq_loyaltycard_program_customer"
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
