# Generated by Django 5.1.15 on 2026-06-22 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("buyer_name", models.CharField(max_length=120)),
                ("buyer_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(blank=True, max_length=120)),
                ("message", models.CharField(blank=True, max_length=300)),
                ("amount_cents", models.PositiveIntegerField()),
                (
                    "payment_state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("stripe_payment_intent", models.CharField(blank=True, max_length=200)),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_purchase",
                        to="loyalty.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
