# Generated by Django 5.1.15 on 2026-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0002_giftvoucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="balance_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
