# Generated by Django 5.1.15 on 2026-07-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0003_voucher_balance_cents"),
        ("promotions", "0021_couponcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="promotions.couponcampaign",
            ),
        ),
    ]
