# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0004_voucher_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltyprogram",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="loyaltyprogram",
            name="reward_label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="voucher",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
