# Generated by Django 5.1.15 on 2026-10-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0005_loyaltyprogram_label_i18n_and_more"),
        ("promotions", "0028_promotion_page_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupons",
                to="promotions.promotion",
            ),
        ),
    ]
