# Generated by Django 5.1.15 on 2026-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0006_t8_3_coupon_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="source_channel",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
