"""Тесты scaffold-моделей вебхуков (SHARED)."""

import pytest

from apps.integrations.webhooks.models import OutgoingWebhook, WebhookDelivery


@pytest.mark.django_db
def test_webhook_gets_autogenerated_secret():
    wh = OutgoingWebhook.objects.create(
        tenant_schema="baeckerei_test",
        url="https://example.test/hook",
        event_types=["promotion.published"],
    )
    assert len(wh.secret) == 64  # token_hex(32)
    assert wh.is_active is True


@pytest.mark.django_db
def test_two_webhooks_have_distinct_secrets():
    a = OutgoingWebhook.objects.create(tenant_schema="t1", url="https://a.test/h")
    b = OutgoingWebhook.objects.create(tenant_schema="t2", url="https://b.test/h")
    assert a.secret != b.secret


@pytest.mark.django_db
def test_delivery_defaults_and_relation():
    wh = OutgoingWebhook.objects.create(tenant_schema="t1", url="https://a.test/h")
    d = WebhookDelivery.objects.create(
        webhook=wh,
        event_type="promotion.published",
        event_id="evt_1",
        payload={"promotion_id": "x"},
    )
    assert d.status == "pending"
    assert d.attempts == 0
    assert wh.deliveries.count() == 1
