# Generated by Django 5.1.15 on 2026-06-22 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=120)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "Alle"),
                            ("stays", "Übernachtung"),
                            ("booking", "Termin"),
                            ("events", "Event"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("per_night", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
    ]
