# Generated by Django 5.1.15 on 2026-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="extra",
            name="image",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
