# Generated by Django 5.1.15 on 2026-07-03 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_extra_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=300, unique=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("folder", models.CharField(blank=True, db_index=True, max_length=40)),
                ("mime_type", models.CharField(blank=True, max_length=40)),
                ("size", models.PositiveIntegerField(default=0)),
                ("alt", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
