# Generated by Django 5.1.15 on 2026-07-03 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_mediaasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("impressum", "Impressum"),
                            ("datenschutz", "Datenschutz"),
                            ("widerruf", "Widerruf"),
                            ("agb", "AGB"),
                        ],
                        max_length=20,
                    ),
                ),
                ("locale", models.CharField(max_length=8)),
                ("text", models.TextField(blank=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "locale"), name="legaldoc_kind_locale_uniq"
                    )
                ],
            },
        ),
    ]
