# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_backfill_owner_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="extra",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
