# Generated by Django 5.1.15 on 2026-08-20 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_extra_label_i18n"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anchor_kind", models.CharField(max_length=16)),
                ("anchor_id", models.UUIDField()),
                ("child_kind", models.CharField(max_length=16)),
                ("child_id", models.UUIDField()),
                ("note", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["anchor_kind", "anchor_id"], name="deallink_anchor_idx"
                    ),
                    models.Index(
                        fields=["child_kind", "child_id"], name="deallink_child_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child_kind", "child_id"),
                        name="deallink_one_anchor_per_child",
                    )
                ],
            },
        ),
    ]
