# Generated by Django 5.1.15 on 2026-08-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_product_slug_product_uniq_product_slug_alive"),
        ("core", "0008_deallink"),
        ("inventory", "0004_stocklocation_alter_stockmovement_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extra",
            name="entity_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="extra",
            name="entity_kind",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="extra",
            name="pool_size",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="extra",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.lieferant",
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="tracker",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Aufpreis"),
                    ("pool", "Eigener Bestand (Pool)"),
                    ("stock", "Lagerartikel"),
                    ("purchase", "Beim Anbieter zu buchen"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="extra",
            name="vat_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
