# Generated by Django 5.1.15 on 2026-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_extra_entity_id_extra_entity_kind_extra_pool_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extra",
            name="consume_qty",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
