# Generated by Django 5.1.15 on 2026-08-13 22:44

import apps.secrets.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("promotions", "0025_promotion_combo_promotion_service_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("passport", "Reisepass"),
                            ("license", "Führerschein"),
                            ("insurance", "Versicherung"),
                            ("visa", "Visum"),
                            ("other", "Sonstiges"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("ref_kind", models.CharField(blank=True, max_length=20)),
                ("ref_id", models.CharField(blank=True, max_length=64)),
                ("path", models.CharField(max_length=255)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("mime", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                ("note", apps.secrets.fields.EncryptedTextField(blank=True)),
                (
                    "uploaded_by",
                    models.CharField(
                        choices=[("customer", "Teilnehmer"), ("staff", "Team")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("consent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="promotions.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "kind"], name="doc_owner_kind_idx"),
                    models.Index(fields=["expires_at"], name="doc_expires_idx"),
                ],
            },
        ),
    ]
