# Generated by Django 5.1.15 on 2026-08-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("promotions", "0026_promotion_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securedocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("receipt", "Beleg / Eingangsrechnung"),
                    ("passport", "Reisepass"),
                    ("license", "Führerschein"),
                    ("insurance", "Versicherung"),
                    ("visa", "Visum"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securedocument",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="promotions.customer",
            ),
        ),
    ]
