# Generated by Django 5.1.15 on 2026-06-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_customdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="site_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
