# Generated by Django 5.1.15 on 2026-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_site_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="disabled_modules",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
