# Generated by Django 5.1.15 on 2026-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenant_disabled_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="provisioning_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="ready",
                max_length=10,
            ),
        ),
    ]
