# Generated by Django 5.1.15 on 2026-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_provisioning_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="small_business",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tax_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
