# Generated by Django 5.1.15 on 2026-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_tenant_small_business_tenant_tax_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="payments_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_connect_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
