# Generated by Django 5.1.15 on 2026-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_tenant_payments_enabled_tenant_stripe_connect_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="orders_prepay",
            field=models.BooleanField(default=False),
        ),
    ]
