# Generated by Django 5.1.15 on 2026-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_optout_existing_from_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="delivery_area",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="delivery_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="delivery_fee_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="delivery_free_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="delivery_min_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
