# Generated by Django 5.1.15 on 2026-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_tenant_delivery_area_tenant_delivery_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="delivery_restrict_to_zones",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="delivery_zones",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pickup_min_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
