# Generated by Django 5.1.15 on 2026-06-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_tenant_delivery_restrict_to_zones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="opening_hours_structured",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
