# Generated by Django 5.1.15 on 2026-06-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_disable_customer_account_for_showrooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="pickup_locations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
