# Generated by Django 5.1.15 on 2026-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0018_tenant_pickup_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="service_area_note",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tenant",
            name="service_area_plz",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
