# Generated by Django 5.1.15 on 2026-07-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0019_tenant_service_area_note_tenant_service_area_plz"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="bank_bic",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="tenant",
            name="bank_holder",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="bank_iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_payment_methods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tenant",
            name="vorkasse_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
