# Generated by Django 5.1.15 on 2026-07-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0020_tenant_bank_bic_tenant_bank_holder_tenant_bank_iban_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="owner_digest_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
