# Generated by Django 5.1.15 on 2026-07-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0021_tenant_owner_digest_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="voucher_max_percent",
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
