# Generated by Django 5.1.15 on 2026-07-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("tenants", "0022_tenant_voucher_max_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="partners.partner",
            ),
        ),
    ]
