# Generated by Django 5.1.15 on 2026-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0024_alter_tenant_business_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("bakery", "Bakery / Bäckerei"),
                    ("butcher", "Butcher / Metzgerei"),
                    ("grocery", "Grocery / Lebensmittel"),
                    ("clothing", "Clothing / Bekleidung"),
                    ("restaurant", "Restaurant"),
                    ("cafe", "Cafe"),
                    ("retail", "Retail / Einzelhandel"),
                    ("online_shop", "Online-Shop"),
                    ("tour_operator", "Tour Operator"),
                    ("hotel", "Hotel"),
                    ("friseur", "Friseur / Salon"),
                    ("handwerker", "Handwerker"),
                    ("werkstatt", "Werkstatt / KFZ"),
                    ("events", "Veranstalter / Events"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
