# Generated by Django 5.1.15 on 2026-07-17 22:17

import apps.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0025_alter_tenant_business_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.tenants.models._new_signup_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password_hash", models.CharField(max_length=128)),
                ("business_name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100)),
                ("business_type", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=100)),
                ("partner_code", models.CharField(blank=True, max_length=40)),
                ("locale", models.CharField(default="de", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_requests",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
