# Generated by Django 5.1.15 on 2026-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0026_signuprequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
