# Generated by Django 5.1.15 on 2026-08-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0028_alter_tenant_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="facebook",
            field=models.CharField(blank=True, max_length=120, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="instagram",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="linkedin",
            field=models.CharField(blank=True, max_length=120, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tiktok",
            field=models.CharField(blank=True, max_length=120, verbose_name="TikTok"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="youtube",
            field=models.CharField(blank=True, max_length=120, verbose_name="YouTube"),
        ),
    ]
