# Generated by Django 5.1.15 on 2026-08-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0029_tenant_socials"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="google_place_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tenant",
            name="google_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="google_rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenant",
            name="google_rating_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
