# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0030_tenant_google_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="opening_hours_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tenant",
            name="service_area_note_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
