# Generated by Django 5.1.15 on 2026-09-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0031_tenant_opening_hours_i18n_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="invoice_b2b_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="invoice_terms_days",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="tenant",
            name="vorkasse_hold_days",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
