# Generated by Django 5.1.15 on 2026-10-09 18:15

from django.db import migrations, models

# T-8.15: слаги демо-тенантов, засеянных до появления флага (заморожено на 2026-10-09:
# все киты seed_demo_tenants, слаг = subdomain или "<key>-demo"). Новые демо помечает
# apply_kit сам.
DEMO_SLUGS = (
    "aktionsmarkt",
    "baeckerei",
    "brueckenblick",
    "cafe",
    "catering",
    "friseur",
    "handwerker",
    "hotel",
    "klingenbrot",
    "metzgerei",
    "mode",
    "moto",
    "ohligser-eck",
    "onlineshop",
    "outlet",
    "pranasy",
    "restaurant-demo",
    "retreat",
    "shop",
    "stadtfuehrung",
    "touren",
    "walder-faden",
    "werkstatt",
    "wupperhof",
)


def mark_demo_tenants(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(slug__in=DEMO_SLUGS).update(is_demo=True)


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0032_sh23_invoice_b2b"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_demo_tenants, migrations.RunPython.noop),
    ]
