# Generated by Django 5.1.15 on 2026-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0033_t8_demo_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email_pending",
            field=models.BooleanField(default=False),
        ),
    ]
