# Generated by Django 5.1.15 on 2026-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0034_t8_5_email_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="in_city_catalog",
            field=models.BooleanField(default=True),
        ),
    ]
