# Generated by Django 5.1.15 on 2026-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0035_t8_6_catalog_hygiene"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="city_category",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
