# Generated by Django 5.1.15 on 2026-06-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0008_promotion_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="is_surprise",
            field=models.BooleanField(default=False),
        ),
    ]
