# Generated by Django 5.1.15 on 2026-06-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0009_promotion_is_surprise"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="recurrence",
            field=models.CharField(
                blank=True,
                choices=[("", "—"), ("daily", "Täglich"), ("weekly", "Wöchentlich")],
                default="",
                max_length=10,
            ),
        ),
    ]
