# Generated by Django 5.1.15 on 2026-06-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0010_promotion_recurrence"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
