# Generated by Django 5.1.15 on 2026-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0011_customer_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_source",
            field=models.CharField(
                choices=[
                    ("reservation", "Reservation"),
                    ("manual", "Manual"),
                    ("import", "Import"),
                ],
                default="reservation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="marketing_opt_in",
            field=models.BooleanField(default=False),
        ),
    ]
