# Generated by Django 5.1.15 on 2026-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0012_customer_created_source_customer_marketing_opt_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_source",
            field=models.CharField(
                choices=[
                    ("reservation", "Reservation"),
                    ("manual", "Manual"),
                    ("import", "Import"),
                    ("order", "Order"),
                ],
                default="reservation",
                max_length=20,
            ),
        ),
    ]
