# Generated by Django 5.1.15 on 2026-06-13 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0013_alter_customer_created_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vouchers",
                to="promotions.customer",
            ),
        ),
    ]
