# Generated by Django 5.1.15 on 2026-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0014_voucher_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="discount_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="voucher",
            name="min_order_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
