# Generated by Django 5.1.15 on 2026-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0015_voucher_discount_cents_voucher_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="group",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
    ]
