# Generated by Django 5.1.15 on 2026-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0016_promotion_group"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Перенос моделей между app'ами БЕЗ DDL: таблицы (promotions_*)
            # физически созданы историческими миграциями promotions и НЕ
            # пересоздаются — данные тенантов целы, свежие схемы получают те же.
            state_operations=[
                migrations.RemoveField(
                    model_name="loyaltycard",
                    name="customer",
                ),
                migrations.RemoveField(
                    model_name="loyaltycard",
                    name="program",
                ),
                migrations.RemoveField(
                    model_name="stampevent",
                    name="card",
                ),
                migrations.RemoveField(
                    model_name="voucher",
                    name="customer",
                ),
                migrations.DeleteModel(
                    name="LoyaltyProgram",
                ),
                migrations.DeleteModel(
                    name="LoyaltyCard",
                ),
                migrations.DeleteModel(
                    name="StampEvent",
                ),
                migrations.DeleteModel(
                    name="Voucher",
                ),
            ],
            database_operations=[],
        ),
    ]
