# Generated by Django 5.1.15 on 2026-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0018_newslettercampaign_customer_marketing_opt_in_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="discount_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatisch"),
                    ("percent", "Prozent-Badge (−30 %)"),
                    ("badge", "Betrag-Badge (−5 €)"),
                    ("strikethrough", "Nur durchgestrichener Preis"),
                    ("festpreis", "Nur neuer Preis (Festpreis)"),
                    ("ab", "Ab-Preis („ab 7,50 €“)"),
                    ("countdown", "Countdown-Akzent"),
                    ("surprise", "Überraschung im Fokus"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
