# Generated by Django 5.1.15 on 2026-07-03 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0020_alter_promotion_discount_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manuell"),
                            ("auto_winback", "Auto Win-back"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("tag", models.CharField(blank=True, default="", max_length=50)),
                ("inactive_days", models.PositiveIntegerField(blank=True, null=True)),
                ("top_ltv", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("discount_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("min_order_cents", models.PositiveIntegerField(default=0)),
                ("valid_days", models.PositiveIntegerField(default=30)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
