# Generated by Django 5.1.15 on 2026-07-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0022_customer_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="couponcampaign",
            name="kind",
            field=models.CharField(
                choices=[
                    ("manual", "Manuell"),
                    ("auto_winback", "Auto Win-back"),
                    ("birthday", "Geburtstag"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
