# Generated by Django 5.1.15 on 2026-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0023_customer_birthday_alter_couponcampaign_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="group_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
