# Generated by Django 5.1.15 on 2026-08-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_service_attributes_i18n_service_faq_i18n"),
        ("catalog", "0022_modifiergroup_display_style_modifieroption_image_and_more"),
        ("promotions", "0024_promotion_group_i18n"),
        ("stays", "0030_stayunit_gap_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotions",
                to="catalog.combo",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotions",
                to="booking.service",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="stay_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotions",
                to="stays.stayunit",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="target_rules",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
