# Generated by Django 5.1.15 on 2026-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0025_promotion_combo_promotion_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("scheduled", "Geplant"),
                    ("active", "Aktiv"),
                    ("paused", "Pausiert"),
                    ("ended", "Beendet"),
                    ("archived", "Archiviert"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
