# Generated by Django 5.1.15 on 2026-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0027_promotion_card_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="page_style",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
