# Generated by Django 5.1.15 on 2026-10-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0028_promotion_page_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionChannelView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel", models.CharField(max_length=30)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_views",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("promotion", "channel"), name="promo_channel_uniq"
                    )
                ],
            },
        ),
    ]
