# Generated by Django 5.1.15 on 2026-07-07 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0013_product_additives"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Wareneingang"),
                            ("sale", "Verkauf"),
                            ("adjustment", "Korrektur"),
                            ("return", "Rückgabe"),
                            ("stocktake", "Inventur"),
                            ("commit", "Materialverbrauch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delta", models.IntegerField(help_text="Signed: +Zugang / −Abgang")),
                ("source", models.CharField(blank=True, max_length=20)),
                ("source_ref", models.CharField(blank=True, max_length=64)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("actor", models.CharField(blank=True, max_length=150)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"], name="stockmove_product_idx"
                    ),
                    models.Index(
                        fields=["source", "source_ref"], name="stockmove_source_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("source_ref", ""), _negated=True),
                        fields=("source", "source_ref", "kind"),
                        name="stockmove_source_ref_uniq",
                    )
                ],
            },
        ),
    ]
