# Generated by Django 5.1.15 on 2026-07-16 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_category_images"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lot_code", models.CharField(blank=True, max_length=64)),
                ("mhd", models.DateField(blank=True, null=True)),
                ("qty_received", models.PositiveIntegerField(default=0)),
                ("qty_remaining", models.IntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["mhd", "created_at"],
                "indexes": [
                    models.Index(fields=["product", "mhd"], name="lot_product_mhd_idx"),
                    models.Index(fields=["variant", "mhd"], name="lot_variant_mhd_idx"),
                ],
            },
        ),
    ]
