# Generated by Django 5.1.15 on 2026-07-16 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_bestellung_lieferant_bestellposition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("receipt", "Wareneingang"),
                    ("sale", "Verkauf"),
                    ("adjustment", "Korrektur"),
                    ("return", "Rückgabe"),
                    ("stocktake", "Inventur"),
                    ("commit", "Materialverbrauch"),
                    ("transfer_out", "Umlagerung (ab)"),
                    ("transfer_in", "Umlagerung (zu)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="inventory.stocklocation",
            ),
        ),
    ]
