# Generated by Django 5.1.15 on 2026-08-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_stocklocation_alter_stockmovement_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestellposition",
            name="qty_returned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("receipt", "Wareneingang"),
                    ("sale", "Verkauf"),
                    ("adjustment", "Korrektur"),
                    ("return", "Rückgabe"),
                    ("stocktake", "Inventur"),
                    ("commit", "Materialverbrauch"),
                    ("transfer_out", "Umlagerung (ab)"),
                    ("transfer_in", "Umlagerung (zu)"),
                    ("return_supplier", "Rücksendung Lieferant"),
                    ("production", "Produktion"),
                ],
                max_length=20,
            ),
        ),
    ]
