# Generated by Django 5.1.15 on 2026-10-09 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_bestellposition_qty_returned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestellposition",
            name="qty_replacement",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Maengelanzeige",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=12, unique=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("inspected_at", models.DateField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=150)),
                ("delivery_note_ref", models.CharField(blank=True, max_length=64)),
                ("result", models.TextField(blank=True)),
                ("inspected_by", models.CharField(blank=True, max_length=150)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                (
                    "bestellung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maengel",
                        to="inventory.bestellung",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mangel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.PositiveIntegerField(default=1)),
                ("defect_types", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("discount", "Annahme mit Preisnachlass"),
                            ("replacement", "Ersatzlieferung"),
                            ("return", "Rücksendung"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("resolved_qty", models.PositiveIntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "anzeige",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maengel",
                        to="inventory.maengelanzeige",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maengel",
                        to="inventory.bestellposition",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
