# Generated by Django 5.1.15 on 2026-06-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deposit_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_state",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="resource",
            name="deposit_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resource",
            name="require_manual_confirm",
            field=models.BooleanField(default=False),
        ),
    ]
