# Generated by Django 5.1.15 on 2026-06-13 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_service_booking_price_cents_booking_service"),
        ("promotions", "0013_alter_customer_created_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(default="Mehrfachkarte", max_length=120)),
                ("code", models.CharField(max_length=12, unique=True)),
                ("credits_total", models.PositiveSmallIntegerField(default=10)),
                ("credits_used", models.PositiveSmallIntegerField(default=0)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passes",
                        to="promotions.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="booking.pass",
            ),
        ),
    ]
