# Generated by Django 5.1.15 on 2026-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_pass_booking_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="counts_party_size",
            field=models.BooleanField(default=False),
        ),
    ]
