# Generated by Django 5.1.15 on 2026-06-15 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_resource_counts_party_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="pass",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passes",
                to="booking.service",
            ),
        ),
        migrations.AddField(
            model_name="pass",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="PassPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(default="Mehrfachkarte", max_length=120)),
                ("credits", models.PositiveSmallIntegerField(default=10)),
                ("price_cents", models.PositiveIntegerField(default=0)),
                ("valid_days", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pass_plans",
                        to="booking.service",
                    ),
                ),
            ],
            options={
                "ordering": ["price_cents", "label"],
            },
        ),
    ]
