# Generated by Django 5.1.15 on 2026-06-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_pass_service_pass_stripe_payment_intent_passplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extras",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
