# Generated by Django 5.1.15 on 2026-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_booking_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
