# Generated by Django 5.1.15 on 2026-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
