# Generated by Django 5.1.15 on 2026-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="photo",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resource",
            name="title",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
