# Generated by Django 5.1.15 on 2026-07-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_resource_bio_resource_photo_resource_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="service",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
