# Generated by Django 5.1.15 on 2026-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_service_description_i18n_service_name_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="attributes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="service",
            name="faq",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="service",
            name="primary_action",
            field=models.CharField(
                blank=True,
                choices=[("booking", "Termin buchen"), ("request", "Anfrage")],
                max_length=10,
            ),
        ),
    ]
