# Generated by Django 5.1.15 on 2026-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_service_attributes_service_faq_and_more"),
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="collections.collection"
            ),
        ),
    ]
