# Generated by Django 5.1.15 on 2026-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0013_service_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="post_visit_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
