# Generated by Django 5.1.15 on 2026-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_booking_post_visit_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="discount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="voucher_code",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
