# Generated by Django 5.1.15 on 2026-07-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_booking_discount_cents_booking_voucher_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
