# Generated by Django 5.1.15 on 2026-07-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_booking_payment_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_video",
            field=models.BooleanField(default=False),
        ),
    ]
