# Generated by Django 5.1.15 on 2026-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_service_season_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="group_code",
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
    ]
