# Generated by Django 5.1.15 on 2026-08-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_booking_group_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="attributes_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="service",
            name="faq_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
