# Generated by Django 5.1.15 on 2026-08-04 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_service_attributes_i18n_service_faq_i18n"),
        ("promotions", "0025_promotion_combo_promotion_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="promotions.promotion",
            ),
        ),
    ]
