# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_booking_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="passplan",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resource",
            name="bio_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resource",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resource",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
