# Generated by Django 5.1.15 on 2026-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_passplan_label_i18n_resource_bio_i18n_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="pricing_mode",
            field=models.CharField(
                blank=True,
                choices=[("", "pro Termin"), ("per_person", "pro Person")],
                default="",
                max_length=12,
            ),
        ),
    ]
