# Generated by Django 5.1.15 on 2026-08-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_service_pricing_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="external_code",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
