# Generated by Django 5.1.15 on 2026-08-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_booking_external_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="invoice_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
