# Generated by Django 5.1.15 on 2026-08-26 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0025_booking_invoice_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="discount_scope",
            field=models.CharField(
                choices=[("deal", "Ganzer Termin"), ("position", "Leistung")],
                default="deal",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=4
            ),
        ),
    ]
