# Generated by Django 5.1.15 on 2026-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0026_booking_discount_scope_booking_vat_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="billing_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="billing_vat_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_type",
            field=models.CharField(
                choices=[("private", "Private"), ("company", "Company")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("on_site", "Barzahlung bei Abholung"),
                    ("stripe", "Online-Zahlung"),
                    ("vorkasse", "Vorkasse (Überweisung)"),
                    ("invoice", "Kauf auf Rechnung"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
