# Generated by Django 5.1.15 on 2026-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0027_sh23_payment_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hide_in_city",
            field=models.BooleanField(default=False),
        ),
    ]
