# Generated by Django 5.1.15 on 2026-06-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="type",
            field=models.CharField(
                choices=[
                    ("log", "Log (internal)"),
                    ("google_business", "Google Business Profile"),
                ],
                default="log",
                max_length=30,
            ),
        ),
    ]
