# Generated by Django 5.1.15 on 2026-06-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0002_alter_channel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="type",
            field=models.CharField(
                choices=[
                    ("log", "Log (internal)"),
                    ("google_business", "Google Business Profile"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                ],
                default="log",
                max_length=30,
            ),
        ),
    ]
