# Generated by Django 5.1.15 on 2026-07-03 05:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0020_alter_promotion_discount_style"),
        ("publishing", "0004_alter_channel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="promotions.promotion",
            ),
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("image", models.JSONField(blank=True, default=dict)),
                ("link_url", models.URLField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="draft", max_length=20),
                ),
                ("source_kind", models.CharField(blank=True, max_length=20)),
                ("source_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"], name="socialpost_due_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="publication",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publications",
                to="publishing.socialpost",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False)),
                fields=("post", "channel"),
                name="publication_post_channel_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("post__isnull", True), ("promotion__isnull", False)),
                    models.Q(("post__isnull", False), ("promotion__isnull", True)),
                    _connector="OR",
                ),
                name="publication_source_xor",
            ),
        ),
    ]
