#!/usr/bin/env python
"""DL-11 «Volle Reihen»: генератор CSS quantity-queries для static/src/app.css.

Сетка несёт data-sf-cols="<тел>/<планш>/<деск>" и data-sf-tail="trim|show|fill"
(siteconfig.grid_attr_string / тег {% grid_attrs %}). На каждом окне ширины
(Tailwind: sm 640, lg 1024; md меняет только gap) число колонок берётся из своей
позиции триплета, поэтому ряд полный и при зуме браузера:

* trim — первый элемент НЕПОЛНОГО последнего ряда и всё за ним скрываются;
  :not(:first-child) оставляет единственный ряд, когда элементов меньше колонок.
* fill — плитка-подсказка .sf-filler (всегда ПОСЛЕДНИЙ ребёнок) растягивается на
  остаток ряда, а при полном ряде прячется.

Исключения: [data-grid].is-list (посетительский «список» <768px — одна колонка) и
[data-density=N] (KAT-4: на ≥1024 колонки задаёт посетитель).

Запуск: `python scripts/gen_fill_rows_css.py` — перезаписывает блок между маркерами
и НЕ трогает остальной файл; затем `npm run build:css`. Замок:
apps/tenants/tests/test_fill_rows.py сверяет блок с выводом генератора.
"""

from __future__ import annotations

import sys
from pathlib import Path

START = "/* DL-11 fill-rows: generated by scripts/gen_fill_rows_css.py — не править руками */"
END = "/* /DL-11 fill-rows */"
CSS_PATH = Path(__file__).resolve().parent.parent / "static" / "src" / "app.css"

WINDOWS = (
    # (media, позиция в триплете → селектор контейнера по N)
    ("@media (max-width: 639.98px)", lambda n: f'[data-sf-cols^="{n}/"]'),
    ("@media (min-width: 640px) and (max-width: 1023.98px)", lambda n: f'[data-sf-cols*="/{n}/"]'),
    ("@media (min-width: 1024px)", lambda n: f'[data-sf-cols$="/{n}"]:not([data-density])'),
    ("@media (min-width: 1024px)", lambda n: f'[data-grid][data-density="{n}"]'),
)


def rules_for(sel: str, n: int) -> list[str]:
    out = []
    # trim: неполный последний ряд — скрыть целиком
    first = f'{sel}[data-sf-tail="trim"]:not(.is-list) > :nth-child({n}n+1):nth-last-child(-n+{n - 1}):not(:first-child)'
    out.append(f"{first},\n{first} ~ * {{ display: none; }}")
    # fill: плитка-подсказка растягивается на остаток ряда; полный ряд → прячется
    out.append(f"{sel} > .sf-filler:nth-child({n}n+1) {{ display: none; }}")
    for r in range(2, n + 1):
        span = n - r + 1
        if span > 1:
            out.append(f"{sel} > .sf-filler:nth-child({n}n+{r}) {{ grid-column: span {span}; }}")
    return out


def generate() -> str:
    lines = [START]
    for media, sel_of in WINDOWS:
        lines.append(f"{media} {{")
        for n in range(2, 7):
            for rule in rules_for(sel_of(n), n):
                lines.append("  " + rule.replace("\n", "\n  "))
        lines.append("}")
    # Посетительский «список» (<768px, одна колонка): плитке-подсказке места нет.
    lines.append(
        "@media (max-width: 767.98px) { [data-grid].is-list > .sf-filler { display: none; } }"
    )
    lines.append(END)
    return "\n".join(lines) + "\n"


def main() -> int:
    css = CSS_PATH.read_text(encoding="utf-8")
    block = generate()
    if START in css and END in css:
        head = css[: css.index(START)]
        tail = css[css.index(END) + len(END) :].lstrip("\n")
        new = head + block + ("\n" + tail if tail else "")
    else:
        new = css.rstrip("\n") + "\n\n" + block
    if "--check" in sys.argv:
        if new != css:
            print("app.css: блок DL-11 устарел — запусти scripts/gen_fill_rows_css.py")
            return 1
        print("ok")
        return 0
    CSS_PATH.write_text(new, encoding="utf-8")
    print(f"wrote {CSS_PATH} ({block.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
