#!/usr/bin/env python
"""DL-11 «Volle Reihen» (+ DL-14 «Verteilen»/авто-колонки/«Alle anzeigen»): генератор
CSS quantity-queries для static/src/app.css.

Сетка несёт data-sf-cols="<тел>/<планш>/<деск>" и data-sf-tail="trim|show|fill"
(siteconfig.grid_attr_string / тег {% grid_attrs %}). На каждом окне ширины
(Tailwind: sm 640, lg 1024; md меняет только gap) число колонок берётся из своей
позиции триплета, поэтому ряд полный и при зуме браузера:

* trim — первый элемент НЕПОЛНОГО последнего ряда и всё за ним скрываются;
  :not(:first-child) оставляет единственный ряд, когда элементов меньше колонок.
* fill — плитка-подсказка .sf-filler (всегда ПОСЛЕДНИЙ ребёнок) растягивается на
  остаток ряда, а при полном ряде прячется.

Исключения: [data-grid].is-list (посетительский «список» <768px — одна колонка) и
[data-density=N] (KAT-4: на ≥1024 колонки задаёт посетитель).

Запуск: `python scripts/gen_fill_rows_css.py` — перезаписывает блок между маркерами
и НЕ трогает остальной файл; затем `npm run build:css`. Замок:
apps/tenants/tests/test_fill_rows.py сверяет блок с выводом генератора.
"""

from __future__ import annotations

import sys
from pathlib import Path

START = "/* DL-11 fill-rows: generated by scripts/gen_fill_rows_css.py — не править руками */"
END = "/* /DL-11 fill-rows */"
CSS_PATH = Path(__file__).resolve().parent.parent / "static" / "src" / "app.css"

WINDOWS = (
    # (media, позиция в триплете → селектор контейнера по N)
    ("@media (max-width: 639.98px)", lambda n: f'[data-sf-cols^="{n}/"]'),
    ("@media (min-width: 640px) and (max-width: 1023.98px)", lambda n: f'[data-sf-cols*="/{n}/"]'),
    ("@media (min-width: 1024px)", lambda n: f'[data-sf-cols$="/{n}"]:not([data-density])'),
    ("@media (min-width: 1024px)", lambda n: f'[data-grid][data-density="{n}"]'),
)


def rules_for(sel: str, n: int) -> list[str]:
    out = []
    # trim: неполный последний ряд — скрыть целиком (сетки БЕЗ хвостовой кнопки)
    first = f'{sel}[data-sf-tail="trim"]:not(.is-list):not([data-sf-more]) > :nth-child({n}n+1):nth-last-child(-n+{n - 1}):not(:first-child)'
    out.append(f"{first},\n{first} ~ * {{ display: none; }}")
    # DL-14 trim + «Alle anzeigen»: последний ребёнок — кнопка .sf-more (не элемент
    # ряда): порог nth-last-child на 1 больше; при скрытии кнопка показывается.
    first_more = f'{sel}[data-sf-tail="trim"][data-sf-more]:not(.is-list) > :nth-child({n}n+1):nth-last-child(-n+{n}):not(:first-child):not(.sf-more)'
    out.append(f"{first_more},\n{first_more} ~ :not(.sf-more) {{ display: none; }}")
    out.append(f"{first_more} ~ .sf-more {{ display: flex; }}")
    # DL-14 spread: число колонок окна — ширина плитки считается в CSS
    out.append(f'{sel}[data-sf-tail="spread"] {{ --sf-n: {n}; }}')
    # DL-14 авто-колонки: атрибут (сервер клампит по числу элементов) сильнее классов
    out.append(f"{sel}[data-sf-auto] {{ grid-template-columns: repeat({n}, minmax(0, 1fr)); }}")
    # fill: плитка-подсказка растягивается на остаток ряда; полный ряд → прячется
    out.append(f"{sel} > .sf-filler:nth-child({n}n+1) {{ display: none; }}")
    for r in range(2, n + 1):
        span = n - r + 1
        if span > 1:
            out.append(f"{sel} > .sf-filler:nth-child({n}n+{r}) {{ grid-column: span {span}; }}")
    return out


def generate() -> str:
    lines = [START]
    for media, sel_of in WINDOWS:
        lines.append(f"{media} {{")
        for n in range(2, 7):
            for rule in rules_for(sel_of(n), n):
                lines.append("  " + rule.replace("\n", "\n  "))
        # spread/auto при одной колонке (телефон): ширина 100 %, сетка в одну колонку
        lines.append(f'  {sel_of(1)}[data-sf-tail="spread"] {{ --sf-n: 1; }}')
        lines.append(
            f"  {sel_of(1)}[data-sf-auto] {{ grid-template-columns: repeat(1, minmax(0, 1fr)); }}"
        )
        lines.append("}")
    # DL-14 spread («Verteilen»): неполный ряд раскладывается по ширине — flex-wrap +
    # space-evenly; ширина плитки = (100% − (n−1)·gap)/n, gap из классов Tailwind
    # контейнера (gap-3/4/6/8, md:gap-6/8). Полный ряд выглядит как сетка.
    # Исключения как у trim/fill: .is-list, [data-density]. Кнопка .sf-more и плитка
    # .sf-filler в этом режиме не нужны.
    lines.append('[data-sf-tail="spread"] { --sf-gap: 1rem; }')
    lines.append('[data-sf-tail="spread"].gap-3 { --sf-gap: 0.75rem; }')
    lines.append('[data-sf-tail="spread"].gap-6 { --sf-gap: 1.5rem; }')
    lines.append('[data-sf-tail="spread"].gap-8 { --sf-gap: 2rem; }')
    lines.append(
        '@media (min-width: 768px) { [data-sf-tail="spread"].md\\:gap-6 { --sf-gap: 1.5rem; } '
        '[data-sf-tail="spread"].md\\:gap-8 { --sf-gap: 2rem; } }'
    )
    lines.append(
        '[data-sf-tail="spread"]:not(.is-list):not([data-density]) { display: flex; flex-wrap: wrap; justify-content: space-evenly; }'
    )
    lines.append(
        '[data-sf-tail="spread"]:not(.is-list):not([data-density]) > * { flex: 0 0 auto; box-sizing: border-box; '
        "width: calc((100% - (var(--sf-n, 1) - 1) * var(--sf-gap)) / var(--sf-n, 1) - 0.02px); }"
    )
    lines.append(
        '[data-sf-tail="spread"] > .sf-filler, [data-sf-tail="spread"] > .sf-more { display: none; }'
    )
    # DL-14 «Alle anzeigen»: кнопка — последний ребёнок сетки, скрыта; trim-правила
    # выше показывают её (display:flex) только когда что-то скрыли; занимает весь ряд.
    lines.append(".sf-more { display: none; grid-column: 1 / -1; justify-content: center; }")
    # Посетительский «список» (<768px, одна колонка): плитке-подсказке места нет.
    lines.append(
        "@media (max-width: 767.98px) { [data-grid].is-list > .sf-filler { display: none; } }"
    )
    lines.append(END)
    return "\n".join(lines) + "\n"


def main() -> int:
    css = CSS_PATH.read_text(encoding="utf-8")
    block = generate()
    if START in css and END in css:
        head = css[: css.index(START)]
        tail = css[css.index(END) + len(END) :].lstrip("\n")
        new = head + block + ("\n" + tail if tail else "")
    else:
        new = css.rstrip("\n") + "\n\n" + block
    if "--check" in sys.argv:
        if new != css:
            print("app.css: блок DL-11 устарел — запусти scripts/gen_fill_rows_css.py")
            return 1
        print("ok")
        return 0
    CSS_PATH.write_text(new, encoding="utf-8")
    print(f"wrote {CSS_PATH} ({block.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
