# Generated by Django 5.1.15 on 2026-06-14 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0014_voucher_customer"),
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("link_token", models.CharField(max_length=48, unique=True)),
                ("chat_id", models.CharField(blank=True, db_index=True, max_length=40)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link",
                        to="promotions.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
