# Generated by Django 5.1.15 on 2026-06-14 19:23

import apps.secrets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_telegramlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="token",
            field=apps.secrets.fields.EncryptedTextField(blank=True, default=""),
        ),
    ]
