# Generated by Django 5.1.15 on 2026-06-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="allergens",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="origin",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
