# Generated by Django 5.1.15 on 2026-06-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productvariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="content_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Stück / —"),
                    ("g", "Gramm"),
                    ("kg", "Kilogramm"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="content_amount",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
