# Generated by Django 5.1.15 on 2026-06-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_modifiergroup_modifieroption"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gtin",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="gtin",
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
