# Generated by Django 5.1.15 on 2026-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_gtin_productvariant_gtin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="badge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("tagesgericht", "Tagesgericht"),
                    ("neu", "Neu"),
                    ("beliebt", "Beliebt"),
                    ("empfehlung", "Empfehlung"),
                ],
                max_length=20,
            ),
        ),
    ]
