# Generated by Django 5.1.15 on 2026-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_combo_combogroup_combooption"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="diets",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
