# Generated by Django 5.1.15 on 2026-06-26 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_diets"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("author_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_published"],
                        name="product_review_pub_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "email"),
                        name="product_review_product_email_uniq",
                    )
                ],
            },
        ),
    ]
