# Generated by Django 5.1.15 on 2026-06-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
