# Generated by Django 5.1.15 on 2026-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="combo",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
