# Generated by Django 5.1.15 on 2026-07-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_combo_description_i18n_combo_name_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additives",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
