# Generated by Django 5.1.15 on 2026-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_additives"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_point",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_target",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="reorder_point",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="reorder_target",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
