# Generated by Django 5.1.15 on 2026-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_product_cost_price_product_reorder_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="origin_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
