# Generated by Django 5.1.15 on 2026-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_product_ingredients_i18n_product_origin_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
