# Generated by Django 5.1.15 on 2026-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_productwaitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="size_table",
            field=models.TextField(blank=True),
        ),
    ]
