# Generated by Django 5.1.15 on 2026-07-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_category_size_table"),
        ("collections", "0002_collection_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="collections.collection"
            ),
        ),
    ]
