# Generated by Django 5.1.15 on 2026-07-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_product_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
