# Generated by Django 5.1.15 on 2026-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_productvariant_color_productvariant_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifiergroup",
            name="display_style",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="modifieroption",
            name="image",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="variant_style",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
