# Generated by Django 5.1.15 on 2026-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_modifiergroup_display_style_modifieroption_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifieroption",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
