# Generated by Django 5.1.15 on 2026-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_modifier_option_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="size_table_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modifiergroup",
            name="name_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modifieroption",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
