# Generated by Django 5.1.15 on 2026-08-13 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_parameters_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="combos",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="event_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="combo",
            name="free_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="combo",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="combo",
            name="min_persons",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combo",
            name="price_per_person",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="combogroup",
            name="included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="course",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
