# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_menu_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="combogroup",
            name="label_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
