# Generated by Django 5.1.15 on 2026-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_combogroup_label_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="page_style",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
