# Generated by Django 5.1.15 on 2026-08-18 12:56
# KAT-3: SEO-слаг товара + бэкфилл живых записей + partial-unique constraint.

from django.db import migrations, models
from django.utils.text import slugify


def backfill_product_slugs(apps, schema_editor):
    """Слаг всем ЖИВЫМ товарам (deleted_at__isnull=True ЯВНО — AliveManager не
    участвует в миграциях). Имя de → первое непустое → sku → 'eintrag';
    коллизии — суффиксом -2, -3… в порядке создания (стабильность нумерации)."""
    Product = apps.get_model("catalog", "Product")
    # Идемпотентность: уже назначенные слаги (частичный прогон) — заняты.
    taken: set[str] = set(
        Product.objects.filter(deleted_at__isnull=True)
        .exclude(slug="")
        .values_list("slug", flat=True)
    )
    qs = (
        Product.objects.filter(deleted_at__isnull=True, slug="")
        .order_by("created_at", "id")
        .only("id", "name", "sku", "slug")
    )
    for p in qs.iterator():
        name = ""
        if isinstance(p.name, dict):
            name = p.name.get("de") or next((v for v in p.name.values() if v), "")
        base = slugify(name or p.sku or "")[:100] or "eintrag"
        if base == "p":  # RESERVED_SLUGS: подпуть /sortiment/p/<slug>/
            base = "p-1"
        slug, i = base, 2
        while slug in taken:
            slug = f"{base}-{i}"
            i += 1
        taken.add(slug)
        p.slug = slug
        p.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0027_category_page_style"),
        ("collections", "0002_collection_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=140),
        ),
        migrations.RunPython(backfill_product_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), models.Q(("slug", ""), _negated=True)
                ),
                fields=("slug",),
                name="uniq_product_slug_alive",
            ),
        ),
    ]
