# Generated by Django 5.1.15 on 2026-08-20 19:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_product_slug_product_uniq_product_slug_alive"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=4
            ),
        ),
    ]
