# Generated by Django 5.1.15 on 2026-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_product_vat_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="primary_action",
            field=models.CharField(
                blank=True,
                choices=[("", "In den Warenkorb"), ("request", "Nur auf Anfrage")],
                default="",
                max_length=10,
            ),
        ),
    ]
