# Generated by Django 5.1.15 on 2026-08-26 17:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_product_primary_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("19.00"), max_digits=4
            ),
        ),
    ]
