# Generated by Django 5.1.15 on 2026-09-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_product_card_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Neu"),
                    ("neu_ohne_ovp", "Neu ohne OVP"),
                    ("ausstellung", "Ausstellungsstück"),
                    ("retoure", "Retoure – geprüft"),
                    ("wie_neu", "Gebraucht – wie neu"),
                    ("gut", "Gebraucht – gut"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="condition_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="condition_note_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="list_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
