# Generated by Django 5.1.15 on 2026-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_outlet_condition_brand_uvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="card_style",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        # Дрейф снимка choices (метки прошли через gettext_lazy в волне I18N-1):
        # DDL не порождает, ставится вместе с полем — прецедент aggregator/0015.
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "keine Angabe"),
                    ("neu", "Neu & originalverpackt"),
                    ("neu_ohne_ovp", "Neu ohne OVP"),
                    ("ausstellung", "Ausstellungsstück"),
                    ("retoure", "Retoure – geprüft"),
                    ("wie_neu", "Gebraucht – wie neu"),
                    ("gut", "Gebraucht – gut"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
