# Generated by Django 5.1.15 on 2026-10-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_category_card_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="city_category",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
