# Generated by Django 5.1.15 on 2026-10-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0035_t8_13b_city_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="hide_in_city",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="hide_in_city",
            field=models.BooleanField(default=False),
        ),
    ]
