# Generated by Django 5.1.15 on 2026-07-01 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_kind",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("service", "Service"),
                            ("stay", "Stay"),
                            ("event", "Event"),
                        ],
                        max_length=16,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("rating", models.PositiveSmallIntegerField()),
                ("author_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_kind", "entity_id", "is_published"],
                        name="review_entity_pub_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_kind", "entity_id", "email"),
                        name="review_entity_email_uniq",
                    )
                ],
            },
        ),
    ]
