# Generated by Django 5.1.15 on 2026-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_backfill_product_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="reply_text",
            field=models.TextField(blank=True),
        ),
    ]
