# Generated by Django 5.1.15 on 2026-08-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_review_replied_at_review_reply_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comment_i18n",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
