# Generated by Django 5.1.15 on 2026-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_review_comment_i18n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="entity_kind",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("service", "Service"),
                    ("stay", "Stay"),
                    ("event", "Event"),
                    ("combo", "Menu set"),
                ],
                max_length=16,
            ),
        ),
    ]
