# Generated by Django 5.1.15 on 2026-08-14 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("promotions", "0025_promotion_combo_promotion_service_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("post", "Beitrag"), ("message", "Nachricht")],
                        default="post",
                        max_length=10,
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        choices=[("web", "Web"), ("telegram", "Telegram")],
                        default="web",
                        max_length=10,
                    ),
                ),
                ("external_ref", models.CharField(blank=True, max_length=64)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "author_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_posts",
                        to="promotions.customer",
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.securedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(blank=True, max_length=120)),
                ("body", models.TextField()),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "author_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_comments",
                        to="promotions.customer",
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.feedpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedSpace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ref_kind", models.CharField(default="event", max_length=20)),
                ("ref_id", models.CharField(db_index=True, max_length=64)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("is_open", models.BooleanField(default=True)),
                ("members_can_post", models.BooleanField(default=True)),
                ("tg_chat_id", models.CharField(blank=True, max_length=40)),
                (
                    "tg_link_code",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("invite_token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ref_kind", "ref_id"), name="feedspace_ref_uniq"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="feedpost",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="community.feedspace",
            ),
        ),
        migrations.AddIndex(
            model_name="feedpost",
            index=models.Index(
                fields=["space", "kind", "created_at"], name="feedpost_space_kind_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feedpost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_ref__gt", "")),
                fields=("space", "external_ref"),
                name="feedpost_external_uniq",
            ),
        ),
    ]
