# Generated by Django 5.1.15 on 2026-06-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                ],
                default="email",
                max_length=20,
            ),
        ),
    ]
